from server.consts.api_consts import ID
from server.consts.data_consts import NAME
from server.consts.audio_features_consts import NUMERIC_AUDIO_FEATURES, KEY
from server.consts.data_consts import URI, TYPE, TRACK_HREF, ANALYSIS_URL, HREF, EXTERNAL_URLS, IMAGES, DURATION_MS, \
    ARTISTS, AVAILABLE_MARKETS, EPISODE, EXTERNAL_IDS, TRACK, ALBUM, PREVIEW_URL, IS_LOCAL, RELEASE_DATE, TOTAL_TRACKS, \
    GENRES, SONG, POPULARITY, ARTIST_POPULARITY, EXPLICIT, ARTIST_FOLLOWERS, RELEASE_YEAR

AUDIO_FEATURES_IRRELEVANT_KEYS = [
    TYPE,
    ID,
    URI,
    TRACK_HREF,
    ANALYSIS_URL
]
ARTISTS_FEATURES_IRRELEVANT_KEYS = [
    EXTERNAL_URLS,
    HREF,
    ID,
    URI,
    IMAGES,
    TYPE
]
TRACKS_FEATURES_IRRELEVANT_KEYS = [
    ARTISTS,
    AVAILABLE_MARKETS,
    DURATION_MS,
    EPISODE,
    EXTERNAL_IDS,
    EXTERNAL_URLS,
    HREF,
    ID,
    TRACK,
    PREVIEW_URL,
    ALBUM,
    IMAGES,
    TYPE,
    ANALYSIS_URL,
    TRACK_HREF,
    IS_LOCAL
]
ALBUM_RELEVANT_FEATURES = [
    NAME,
    RELEASE_DATE,
    TOTAL_TRACKS
]
NON_NUMERIC_COLUMNS = [
    URI,
    GENRES,
    SONG
]
CATEGORICAL_COLUMNS = [
    KEY
]
PLAYLIST_IRRELEVANT_COLUMNS = NON_NUMERIC_COLUMNS + CATEGORICAL_COLUMNS
NON_AUDIO_DATABASE_COLUMNS = [
    POPULARITY,
    ARTIST_POPULARITY,
    ARTIST_FOLLOWERS,
    EXPLICIT,
    RELEASE_YEAR
] + NON_NUMERIC_COLUMNS
DATABASE_COLUMNS = NUMERIC_AUDIO_FEATURES + NON_AUDIO_DATABASE_COLUMNS
SIMILARITY_SCORE = 'similarity_score'
N_MOST_COMMON_GENRES = 4
SIMILARITY_SCORE_THRESHOLD = 0.85
NUMERIC_RANGE_FILTER_COLUMNS = [
    RELEASE_YEAR,
    POPULARITY,
    ARTIST_POPULARITY
]
HAS_RELEVANT_GENRES = 'has_relevant_genres'
