name: verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
#    - name: Run Milvus
#      shell: bash
#      run: |
#        wget https://raw.githubusercontent.com/milvus-io/milvus/master/scripts/standalone_embed.sh
#        bash standalone_embed.sh start
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: |
          ffmpeg \
          libfontconfig1 \
          libice6 \
          libsm6 \
          libxext6 \
          libxrender1 \
          tesseract-ocr \
          tesseract-ocr-eng \
          *libarchive13*
        version: 1.0
    - name: Install dependencies
      run: |
        pip install poetry==1.6.1
        poetry export -f requirements.txt --with dev --output requirements.txt --without-hashes
        pip install -r requirements.txt
        pip install pytest-cov
    - name: Test with pytest
      run: |
        pytest tests --asyncio-mode=auto --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
